scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.5585054
        upper_angle: 0.837758
        invert: false
    filter2:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 2.303835
        upper_angle: 2.600541
        invert: false
    filter3:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 3.787364
        upper_angle: 4.049164
        invert: false
    filter4:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 5.393067
        upper_angle: 5.654867
        invert: false