---
# Default joystick config for an XBOX Series X/S Controller
# If you want to use a PS3 controller or other, consider creating another .yaml file

joy_node:
  ros__parameters:
    device_id: 0  # ID connection /dev
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick vertical (Xbox)
    scale_linear:
      x: 0.28  # m/s
    scale_linear_turbo:
      x: 0.33  # m/s

    axis_angular:
      yaw: 0  # Left stick horizontal (Xbox)
    scale_angular:
      yaw: 0.5  # rad/s
    scale_angular_turbo:
      yaw: 1.0  # rad/s

    # Deadman switch enabled — robot responds only when holding RB button
    # enable_button: 2        # X button
    # enable_turbo_button: 5  # RB button
    # require_enable_button: true
